[package]
name = "simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
network-parser = { git = "https://github.com/cndolo/lightning-simulator", rev ="ad28a2e"}
lightning-simulator = { git = "https://github.com/cndolo/lightning-simulator", rev ="ad28a2e"}
clap = { version = "4.0.22"}

[[bin]]
name = "simulator"
path = "src/bin/main.rs"
