name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        name: ⚙ Install stable toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 🔬 Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.30.0
          args: '--exclude-files src/bin/*'

      - name: 🆙 Upload to codecov.io
        uses: codecov/codecov-action@v4

      - name: 💾 Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cobertura.xml
