name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:

    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 🔬 Generate code coverage
        run: |
          cargo tarpaulin --release --exclude-files src/bin/* --out xml

      - name: 🆙 Upload to codecov.io
        uses: codecov/codecov-action@v4
